spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finaltest
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


mybatis-plus:
  #01.使用当前文件中的信息，但是，要么使用xml中的，要么使用yaml中的，不可以两个都加载
  #就是，要么config-location,要么configuration
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  #02.开始驼峰命名，可以在mybatis-config.xml配置，同时也可以在当前地址下配置
  #指定mybatis全局配置文件中的相关配置
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8888